-- Options that are not Neovim defaults.
-- Gone from the old vimrc because they are defaults now: nocompatible,
-- filetype/syntax on, autoread, backspace, hidden, hlsearch, incsearch,
-- laststatus=2, nobackup, smarttab, wildmenu, formatoptions+=j,
-- nojoinspaces, history, encoding, undodir (~/.local/state/nvim/undo).

local o = vim.o
local opt = vim.opt

-- Trailing comments are column-aligned by hand; stylua collapses them to
-- a single space, so it is switched off for the whole settings block.
-- stylua: ignore start

-- Colors
o.termguicolors = true          -- solarized.nvim is a truecolor theme
o.background = "dark"

-- UI
o.number = true                 -- Show line numbers
o.cursorline = true             -- Highlight current line
o.title = true                  -- Show the filename in the window titlebar
o.showmatch = true              -- Show matching brackets/parenthesis
o.winminheight = 0              -- Allow windows to be squashed to just a status bar
o.mouse = "a"                   -- Enable mouse in all modes
o.list = true                   -- Show "invisible" characters
opt.listchars = { tab = "▸ ", trail = "•", extends = ">", precedes = "<", nbsp = "." }
opt.shortmess:append("filmnrxoOtTIc") -- Abbrev. of messages (avoids 'hit enter')

-- Movement and scrolling
o.scrolljump = 5                -- Lines to scroll when cursor leaves screen
o.scrolloff = 1                 -- Minimum lines to keep above and below cursor
o.virtualedit = "onemore"       -- Allow for cursor beyond last character
o.whichwrap = "b,s,<,>,[,]"     -- Cursor keys wrap too
opt.matchpairs:append("<:>")    -- Match, to be used with %

-- Indentation and formatting
o.wrap = false                  -- Do not wrap long lines
o.shiftwidth = 4                -- Use indents of 4 spaces
o.tabstop = 4                   -- An indentation every four columns
o.softtabstop = 4               -- Let backspace delete indent
o.expandtab = true              -- Tabs are spaces, not tabs

-- Search
o.ignorecase = true             -- Case insensitive search
o.smartcase = true              -- Case sensitive when search contains upper case
o.grepprg = "rg -uu --color=never --vimgrep --no-heading"
o.grepformat = "%f:%l:%c:%m,%f:%l:%m"

-- Windows
o.splitright = true             -- Puts new vsplit windows to the right of the current
o.splitbelow = true             -- Puts new split windows to the bottom of the current

-- Files
o.swapfile = false              -- Dont create swap files
o.undofile = true               -- Persistent undo
o.clipboard = "unnamed,unnamedplus" -- Connect clipboard registers * and + to default register
o.modeline = true
o.modelineexpr = true           -- Allow fde= etc. in modelines
opt.tags:prepend("./.git/tags;") -- Tags generated by the git_template hooks

-- Command line
o.wildmode = "list:longest,full"

-- Folding via treesitter (foldlevel high = don't fold by default)
o.foldlevel = 99
o.foldlevelstart = 99
o.foldmethod = "expr"
o.foldexpr = "v:lua.vim.treesitter.foldexpr()"

-- Time until CursorHold fires (diagnostics echo, see autocmds.lua)
o.updatetime = 800

-- stylua: ignore end
